defaults:
- _self_
hydra:
  run:
    dir: logs
inference:
  ckpt_path: checkpoints/RNA3DB.ckpt
  input_dir: Inputs
  output_dir: Predictions
  name: Dummy
  num_gpus: 1
  interpolant:
    sampling:
      num_timesteps: 50
  samples:
    samples_per_sequence: 2
