data_cfg:
  train_dir: ./ready_to_train/train_set
  val_dir: ./ready_to_train/test_set
  csv_path: metadata/rna_metadata.csv
  filtering:
    max_len: 200
    min_len: 30
  min_t: 0.01
  samples_per_eval_length: 1
  num_eval_lengths: 1
  batch_size: 1
  max_batch_size: 1
  max_squared_res: 375000
  max_num_res_squared: 375000
  eval_batch_size: 16
  num_workers: 8
  prefetch_factor: 100
interpolant:
  min_t: 0.01
  rots:
    train_schedule: linear
    sample_schedule: exp
    exp_rate: 10
  trans:
    train_schedule: linear
    sample_schedule: linear
  sampling:
    num_timesteps: 50
  self_condition: ${model.edge_features.self_condition}
model:
  node_embed_size: 256
  edge_embed_size: 128
  symmetric: false
  node_features:
    c_s: ${model.node_embed_size}
    c_pos_emb: 128
    c_timestep_emb: 128
    embed_diffuse_mask: false
    max_num_res: 2000
    timestep_int: 1000
  edge_features:
    single_bias_transition_n: 2
    c_s: ${model.node_embed_size}
    c_p: ${model.edge_embed_size}
    relpos_k: 64
    use_rbf: true
    num_rbf: 32
    feat_dim: 64
    num_bins: 22
    self_condition: true
  ipa:
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 128
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 6
    ss: 3
    dropout: 0.1
experiment:
  debug: false
  seed: 123
  num_devices: 4
  gpu_num: 7
  warm_start: null
  warm_start_cfg_override: false
  use_swa: false
  batch_ot:
    enabled: true
    cost: kabsch
    noise_per_sample: 1
    permute: false
  training:
    min_plddt_mask: null
    loss: se3_vf_loss
    bb_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 1.0
    aux_loss_t_pass: 0.25
    tors_loss_scale: 1.0
    num_non_frame_atoms: 1
  wandb:
    name: debugging
    project: RNApiFlow
    save_code: false
    tags: []
    mode: online
  optimizer:
    lr: 0.0001
  trainer:
    overfit_batches: 0
    min_epochs: 2
    max_epochs: 100
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: true
    strategy: ddp
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 1
  checkpoints:
    dirpath: checkpoints/
    filename: '{epoch:03d}-{step:06d}'
    save_last: true
    save_top_k: 15
    monitor: train/loss
    mode: min
    every_n_epochs: 1
folding_cfg: null
